version: "3.5"

services:
  node-api:
    container_name: kjk-app
    restart: always
    ports:
      - "3000:3000"
    image: kjk-server
    build: ./
    environment:
      - NODE_ENV=production
#    networks:
#      - kjk-network
#
#  mongo-db:
#    image: mongo
#    container_name: kjk-mongo-db
#    ports:
#      - "27017-27019:27017-27019"
#    networks:
#      - kjk-network
#
#networks:
#  kjk-network:
#    name: kjk-network
#    driver: bridge